name: Documentation

on:
  push:
    branches: ["main"]
    paths:
      - "packages/omero-screen-plots/docs/**"
      - "packages/omero-screen-plots/src/**"
      - ".github/workflows/docs.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "packages/omero-screen-plots/docs/**"
      - "packages/omero-screen-plots/src/**"
  # Also run after successful releases
  workflow_run:
    workflows: ["Release"]
    types:
      - completed
    branches: [main]

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock

      - name: Set up Python
        run: uv python install 3.12

      - name: Create virtual environment and install dependencies
        run: |
          # Create virtual environment
          uv venv
          # Install documentation requirements
          uv pip install -r packages/omero-screen-plots/docs/requirements.txt
          # Install package in development mode
          uv pip install -e packages/omero-screen-plots

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Build documentation
        run: |
          cd packages/omero-screen-plots/docs
          # Build the documentation with plot generation enabled
          uv run sphinx-build -b html . _build/html
        env:
          # Enable plot generation for complete documentation
          BUILD_PLOTS: true
          # Use headless display for matplotlib in CI
          MPLBACKEND: Agg

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: packages/omero-screen-plots/docs/_build/html

  # Deploy job
  deploy:
    # Deploy on pushes to main or after successful releases
    if: |
      (github.ref == 'refs/heads/main' && github.event_name == 'push') ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
